### ISSUE TITLE
Multiple simultaneous trainings

### ISSUE THREAD

**Issue by Connor-Bowley** [mturja-vf-ic-bd/SlicerDeepLearningUI#11]
I am guessing you do not want to support multiple trainings at the same time. Right now I can keep clicking `Start Trainer` over and and over and it will do a bunch of stuff at the same time. Considering the output directory is the same for each, I would think that is a bad thing.

One way to deal with this is to disable the UI while it is training.

Example:
```
self.ui.writeDirLineEdit.enabled = False
self.ui.tbPortLineEdit.enabled = False
```

Don't forget to set the `enabled`s back to true when training is complete.

**Comment by mturja-vf-ic-bd** [comment]
Hi Connor,
I actually do want to support multiple training because I don't want the user to wait till the training ends (which can take hours to days). In that case, the user has to change the log directory which is annoying for the user. I guess a better way is to check if the directory exists and if so, tell the user to change it. What do you think?

**Comment by Connor-Bowley** [comment]
How do you expect multiple training to work? If you are training 10 nets at once, is it going to train slower than 10 nets sequentially because you are using too many threads? Are the trainings multithreaded in and of themselves?

What do you want to allow the user to do while training is happening?

I do think that a pop up asking the user if they want to overwrite the log directory if it already exists could be nice.

**Comment by Connor-Bowley** [comment]
Correct.

**Comment by mturja-vf-ic-bd** [comment]
Disabled Start_Train button after training starts to allow only instances of training at a particular time.
